### ISSUE TITLE
 Singleton UseCase?

### ISSUE THREAD

**Issue by AntonKulykov** [eetech/clean-architecture-android-kotlin#1]
```
    @Provides
    @Singleton
    internal fun provideGetArticlesListUseCase(articlesRepository: ArticlesRepository, @Named("ioScheduler") ioScheduler: Scheduler, @Named("mainThreadScheduler") mainThreadScheduler: Scheduler): GetArticlesListUseCase =
            GetArticlesListUseCase(articlesRepository, ioScheduler, mainThreadScheduler)
```

I think the `@Singleton` annotation is superfluous, because `onDestroy` we do a dispose of `CompositeDisposable`, therefore we can not perform the request again.

**Comment by patrickyin** [comment]
I think the Rx subscription may not be related to singleton use case.

The Rx subscription will be disposed when `Activity`'s lifecycle goes to `onDestroy`, but it won't destroy the use case instance. The whole idea is each use case responsible for a different business logic, and it can be shared between multiple Presenters. 

e.g.
`ArticleListPresenter` is a consumer of `GetArticleListUseCase` and `GetArticleTypeUseCase`, it shows articles list and types list on that screen.
Imagine we got another screen, then we have a presenter called `DashboardPresenter`, this screen shows multiple sections(article list, user list, message list), so this  DashboardPresenter is a consumer of `GetArticleListUseCase` too, the first time when user open article list screen, `GetArticleListUseCase` makes a network request and then hold the data, on the next screen, the  `DashboardPresenter` uses the same UseCase instance rather than create a new instance, it would have a better performance(it doesn't need to make a new network call). and it can be shared data between multiple screens.

**Comment by AntonKulykov** [comment]
The idea is good, but your implementation will not allow it. Your use case is not a memory cache, it will perform a repeated network call when you call execute. But rotate the screen or press back and open the application and your network call will be canceled at all, because you called it after `dispose()`. Perhaps you need to recreate `CompositeDisposable`, or you can use the `clear()`.

**Comment by patrickyin** [comment]
That is an example and I didn't implement the memory cache on domain layer at the moment, the current use case doesn't have memory cache, it will make a new call every time when the consumer subscribes it, we could simply add `.replay()` to the Rx chain, then it won't make new request after the first network call.

For the 2nd issue you mentioned: 
Yes, I agree, the current use case is a singleton object, the use case and `CompositeDisposable` won't be re-created after rotates. I didn't notice that before. Thanks for your contribution @AntonKulykov , I'll fix it.
